### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [babydots/immersivelock#1]
https://hosted.weblate.org/projects/babyphone/immersive-lock/#information is
LGPLv3
whereas https://hosted.weblate.org/projects/babyphone/immersive-lock/#information states
GPLv3

It can be changed in https://hosted.weblate.org/settings/babyphone/immersive-lock/

**Comment by pserwylo** [comment]
Think I've fixed it. Thanks for your early and numerous contributions as always. It may sound minor, but having someone sanoty check the process, log bugs, and contribute early translations really gets the ball moving.

Inevitebly with my other apps, once I've published that first version on FDroid with "I18n: Norweigan translation added" in the changelog, I feel that it then triggers others to come and contribute too! That in turn then results in quick rapid releases with "New translation added", pushing it on the front page of FDroid, which triggers more wonderful contributions.

So yes, you're contributing a lot more than just a new language when you do this.

**Comment by comradekingu** [comment]
@pserwylo 
Thank you. That is exactly what I try to do.
If you add "kingu" in https://hosted.weblate.org/access/babyphone/#users I can find other things to fix, and sort out the
libre requirements, etc.

**Comment by pserwylo** [comment]
Arg, I now realise I got in a pickle with this library.

I will now:
 * Remove the https://hosted.weblate.org/projects/babyphone/immersive-lock/ component.
 * Refactor baby**phone** and baby**dots** to use the library.
 * Ensure that the latest greatest translations are copied from baby**dots** to babydots/immersivelock.
 * Create a new weblate project for the immersivelock library (or do you think I should just add it as a component to the baby**dots** weblate project where the most translations live?).

Backstory:
 * Started with this functionality in [baby**dots**](https://github.com/babydots/babydots).
 * Copied the functionality to [baby**phone**](https://github.com/babydots/babyphone).
 * Realised it would be used in more than one app, extracted to a library in [baby**phone/immersivelock**](https://github.com/babydots/babyphone).
 * Wanted to use the library in [baby**book**](https://github.com/babydots/babybook).
 * Realised it was awkward to depend on the library in the baby**phone** repo, so created the [babydots/**immersivelock**](https://github.com/babydots/immersivelock) **library** and used that in baby**phone**. When doing so, manually copied translations from baby**dots** because it was the most established, and had the most languages.
 * Crucially, I **never went back and refactored babydots or babyphone to use the new library**.

**Comment by comradekingu** [comment]
Fewer projects seems better. Helps with people subscribing to something that exists already.

As a sidenote, you can turn on internal sharing in Weblate between components.

There are sharing options per component in the plugins:
https://hosted.weblate.org/addons/babyphone/android-strings/
https://docs.weblate.org/no/latest/admin/addons.html#addon-weblate-autotranslate-autotranslate

And this for translation memory on the whole instance:
https://hosted.weblate.org/settings/babyphone/#workflow
https://docs.weblate.org/no/latest/admin/projects.html#project-use-shared-tm

I don't think dictionaries are needed for either project.(?)
If so
https://hosted.weblate.org/projects/babydots/glossary/ and
https://hosted.weblate.org/projects/babyphone/glossary/
can be deleted.

**Comment by pserwylo** [comment]
Thanks. I've actioned each of these recommendations.

I've also added the immersive-lock-library to babydots: https://hosted.weblate.org/projects/babydots/immersive-lock-library/ with appropriate screenshots/descriptions. I then updated the source code for babyphone + babydots to use this library so they all officially share the one set of translations (as does babybook - which I'll add to weblate soon).
